# Generated by Django 4.2 on 2023-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('data_lancamento', models.DateField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('estudio', models.CharField(max_length=50)),
                ('diretor', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, default='', upload_to='animes/covers/%Y/%m/%d')),
                ('generos', models.ManyToManyField(to='animes.genero')),
            ],
        ),
    ]
