# Generated by Django 4.2 on 2023-04-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeS',
            new_name='Anime',
        ),
    ]
