# Generated by Django 4.2 on 2023-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_rename_animes_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='nome_alternativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
