# Generated by Django 4.2 on 2023-04-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_anime_nome_alternativo_alter_anime_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='animes/covers/%Y/%m/%d'),
        ),
    ]
