# Generated by Django 4.2 on 2023-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_anime_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='dublagem',
            field=models.BooleanField(default=False),
        ),
    ]
